#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "molokai"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false

[[layers]]
  name = "colorscheme"

[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "smart"

[[layers]]
  name = "lsp"

[[layers]]
  name = "fzf"

[[layers]]
  name = "tools"

[[layers]]
  name             = 'shell'
  default_position = 'top'
  default_height   = 30

[[layers]]
  name = "git"

[[layers]]
  name = "debug"

[[layers]]
  name = "checkers"
  lint_on_the_fly = true

[[layers]]
  name = "format"
  format_on_save = true

[[layers]]
  name = "lang#python"
  enable_typeinfo = true

[[layers]]
  name = "lang#toml"

[[layers]]
  name = "lang#latex"

[[layers]]
  name = "lang#java"

[[layers]]
  name = "lang#c"

[[layers]]
  name = "lang#markdown"

[[layers]]
  name = "lang#sh"

[[layers]]
  name = "lang#rust"
  recommended_style = true







#[[custom_plugins]]
#  repo = ""
#  merged = 0
