#!/usr/bin/env sh
#
# ~/.config/aliasrc
#

alias ls="ls -hN --color=auto --group-directories-first" \
			grep="grep --color=auto" \
			fgrep="fgrep --color=auto" \
			egrep="egrep --color=auto" \
			diff="diff --color=auto" \
  		df="df -h" \
			wget="wget --hsts-file=$HOME/.config/.wget-hsts" \
  		config="/usr/bin/git --git-dir=/home/trim/.cfg/ --work-tree=/home/trim" \
  		microcode="grep . /sys/devices/system/cpu/vulnerabilities/*" \
			backup="sudo timeshift --check" \
  		update-grub="sudo grub-mkconfig -o /boot/grub/grub.cfg" \
			update-mirrorlist="sudo reflector --protocol https --sort rate --save /etc/pacman.d/mirrorlist" \
  		update="sudo pacman -Syyu" \
			cleanup="sudo pacman -Rsn \$(pacman -Qtdq)"\
  		fc="sudo fc-cache -fv" \
			vim="nvim" \
			v="$EDITOR" \
			ccat="highlight --out-format=ansi" \
			calcurse="calcurse -D ~/.config/calcurse" \
  		S="sudo" \
  		o="exo-open" \
			del="trash"
