#!/usr/bin/env sh
#
# ~/.config/aliasrc
#

# Look and feel
alias ls="ls -hv --color=auto --group-directories-first" \
			grep="grep --color=auto" \
			fgrep="fgrep --color=auto" \
			egrep="egrep --color=auto" \
			diff="diff --color=auto" \
  		df="df -h" \
			v="emacs -nw"


# Shortcuts
alias cleanup="sudo pacman -Rsn \$(pacman -Qtdq)"\
			dot="/usr/bin/git --git-dir='$HOME/.config/git-bare-repo/' --work-tree='$HOME'" \
			conf="nvim \$(find ~/.config/ -maxdepth 2 -type f | fzf --height=30% --reverse)" \
			scripts="nvim \$(find ~/.local/bin -maxdepth 2 -type f | fzf --height=30% --reverse)" \
			snapch="sudo timeshift --check" \
			snapcr="sudo timeshift --create" \
			ccat="highlight --out-format=ansi" \
  		o="xdg-open" \
			dlrecs="ethvid-scraper -q low -f '/home/trim/Documents/Uni/6.Semester/Lecture Recordings/LectureURLS' -d '/home/trim/Documents/Uni/6.Semester/Lecture Recordings/'" \
			mnt="udisksctl mount -b" \
			umnt="udisksctl unmount -b" \
			killtty="sudo pkill -9 -t" #ttyID comes here; see w

# Less often used shortcuts
alias microcode="grep . /sys/devices/system/cpu/vulnerabilities/*" \
  		update-grub="sudo grub-mkconfig -o /boot/grub/grub.cfg" \
			update-mirrorlist="sudo reflector --protocol https --sort rate --save /etc/pacman.d/mirrorlist" \
  		fc="sudo fc-cache -fv" \
			whitenoise="play -n synth brownnoise synth pinknoise mix synth sine amod 0.3 10"

# Clean home dir
alias wget="wget --hsts-file='\$HOME/.config/.wget-hsts'" \
			feh="feh --no-fehbg"
