#! /bin/sh

# If refreshing bspwm, remove all previous rules to prevent doubling up.
bspc rule -r "*"

#create virtual desktops
bspc monitor -d          

bspc config focused_border_color "#E1B037"
bspc config normal_border_color "#00001C"
bspc config urgent_border_color "#7C0068"

bspc config border_width         2
bspc config window_gap          3

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config remove_disabled_monitors 	 true
bspc config remove_unplugged_monitors 	 true

bspc config automatic_scheme longest_side
bspc config initial_polarity second_child

bspc config removal_adjustment      false

#window rules
bspc rule -a st:floating state=floating
bspc rule -a "edu-mit-csail-sdg-alloy4whole-SimpleGUI" state=floating
bspc rule -a brave-browser desktop='^3' follow=on
bspc rule -a Zathura desktop='^5' state=tiled follow=on 
bspc rule -a mpv desktop='^8' follow=on
bspc rule -a Thunderbird desktop='^6' follow=on
bspc rule -a Steam desktop='^7' follow=off
bspc rule -a Screenkey manage=off
bspc rule -a Pavucontrol state=floating
bspc rule -a discord desktop='^6'
bspc rule -a Blueman-manager state=floating
#Not working
#bspc rule -a *:"Spotify Free" desktop='^8' follow=on
#bspc rule -a 'Gimp-2.10' desktop='^8' follow=on

#wm specific autostart
xsetroot -cursor_name left_ptr
sxhkd &
polybar --reload main &
