#! /bin/sh

#wm specific autostart
sxhkd &
polybar main &
xsetroot -cursor_name left_ptr

#create virtual desktops
bspc monitor -d          

bspc config border_width         2
bspc config window_gap          5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#window rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Screenkey manage=off
